# Generated by Django 6.0.3 on 2026-05-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_manager_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='money_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
