# Generated by Django 6.0.3 on 2026-05-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_review_is_visible'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('money_balance__gte', 0)), name='check_positive_money_balance'),
        ),
    ]
