# Generated by Django 6.0.3 on 2026-05-29 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_lessonmaterial_options_and_more'),
        ('users', '0006_student_check_positive_money_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.CreateModel(
            name='StudentDisciplineLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_levels', to='inventory.discipline')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentlevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_levels', to='users.student')),
            ],
            options={
                'verbose_name': 'Рівень студента з дисципліни',
                'verbose_name_plural': 'Рівні студентів з дисциплін',
                'unique_together': {('student', 'discipline')},
            },
        ),
    ]
