# Generated by Django 6.0.3 on 2026-05-21 19:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('inventory', '0001_initial'), ('inventory', '0002_initial'), ('inventory', '0003_remove_slot_is_booked_slot_status_and_more'), ('inventory', '0004_journalrecord_grade_and_more'), ('inventory', '0005_remove_slot_inventory_s_teacher_d45cf3_idx_and_more'), ('inventory', '0006_packageplan'), ('inventory', '0007_learning_request'), ('inventory', '0008_material')]

    dependencies = [
        ('users', '0006_student_check_positive_money_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_lessons_course', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('theory_material_url', models.CharField(blank=True, max_length=255, null=True)),
                ('default_homework', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lessons_count', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('earned_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_discount_used', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.discipline'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='scheduled', max_length=50)),
                ('meeting_link', models.CharField(blank=True, max_length=255, null=True)),
                ('curriculum_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.curriculumlesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='JournalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('teacher_homework_task', models.TextField(blank=True, null=True)),
                ('homework_answer_url', models.CharField(blank=True, max_length=255, null=True)),
                ('homework_grade', models.IntegerField(blank=True, null=True)),
                ('activity_grade', models.IntegerField(blank=True, null=True)),
                ('teacher_notes', models.TextField(blank=True, null=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.IntegerField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.coursecompletion')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.course')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.package'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.slot'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.discipline')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacherlevel')),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.teacher'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('level_topics', models.CharField(blank=True, max_length=50, null=True)),
                ('order_index', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.course')),
            ],
        ),
        migrations.AddField(
            model_name='curriculumlesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.topic'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_penalty', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='slot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['teacher', 'start_time'], name='inventory_s_teacher_d45cf3_idx'),
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='grade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='journalrecord',
            name='teacher_homework_task',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('conducted', 'Conducted'), ('student_missed', 'Student Missed'), ('teacher_missed', 'Teacher Missed'), ('canceled_advance', 'Canceled in Advance')], default='scheduled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='journalrecord',
            index=models.Index(fields=['is_present'], name='inventory_j_is_pres_f79f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['student', 'status'], name='inventory_l_student_3e92e1_idx'),
        ),
        migrations.RemoveIndex(
            model_name='slot',
            name='inventory_s_teacher_d45cf3_idx',
        ),
        migrations.AddField(
            model_name='course',
            name='discount_milestones',
            field=models.JSONField(blank=True, default=dict, help_text='Логіка: {"85": 5, "91": 10, "96": 15}. Ключ — мінімальний бал для отримання відсотка знижки.', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='inventory.discipline'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='inventory.course'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='earned_discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='is_discount_used',
            field=models.BooleanField(default=False, help_text='True, якщо бонуси за цей курс уже були використані для оплати пакета'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='users.student'),
        ),
        migrations.AlterField(
            model_name='curriculumlesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_lessons', to='inventory.topic'),
        ),
        migrations.AlterField(
            model_name='journalrecord',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='inventory.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='inventory.package'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='inventory.slot'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.student'),
        ),
        migrations.AlterField(
            model_name='package',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='users.student'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='inventory.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='inventory.discipline'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='inventory.course'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.teacher'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'discipline'], name='inventory_c_is_acti_d1ad7c_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecompletion',
            index=models.Index(fields=['student', 'is_discount_used'], name='inventory_c_student_fef074_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['student', 'status'], name='inventory_p_student_869b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['teacher', 'start_time', 'status'], name='inventory_s_teacher_530bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['teacher', 'created_at'], name='inventory_t_teacher_5ddee3_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursecompletion',
            constraint=models.CheckConstraint(condition=models.Q(('earned_discount__gte', 0), ('earned_discount__lte', 100)), name='check_valid_earned_discount'),
        ),
        migrations.AddConstraint(
            model_name='coursecompletion',
            constraint=models.CheckConstraint(condition=models.Q(('completed_lessons_count__gte', 0)), name='check_positive_completed_lessons'),
        ),
        migrations.AddConstraint(
            model_name='journalrecord',
            constraint=models.CheckConstraint(condition=models.Q(('grade__isnull', True), models.Q(('grade__gte', 1), ('grade__lte', 10)), _connector='OR'), name='check_valid_grade_range'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='check_positive_package_balance'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='check_valid_slot_time_range'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='check_positive_transaction_amount'),
        ),
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_lessons', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['total_lessons'],
            },
        ),
        migrations.CreateModel(
            name='LearningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('english', 'Англійська мова'), ('math', 'Математика'), ('ukrainian', 'Українська мова'), ('history', 'Історія України'), ('informatics', 'Інформатика')], max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('preferred_days', models.CharField(blank=True, default='', max_length=200)),
                ('preferred_time', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('matched', 'Підібрано викладача'), ('cancelled', 'Скасовано')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_requests', to='inventory.package')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_requests', to='users.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='inventory.teacher')),
            ],
        ),
    ]
