# Generated by Django 6.0.3 on 2026-04-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['teacher', 'start_time'], name='inventory_s_teacher_d45cf3_idx'),
        ),
    ]
