# Generated by Django 6.0.3 on 2026-04-28 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_slot_is_booked_slot_status_and_more'),
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalrecord',
            name='grade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='journalrecord',
            name='teacher_homework_task',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('conducted', 'Conducted'), ('student_missed', 'Student Missed'), ('teacher_missed', 'Teacher Missed'), ('canceled_advance', 'Canceled in Advance')], default='scheduled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='journalrecord',
            index=models.Index(fields=['is_present'], name='inventory_j_is_pres_f79f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['student', 'status'], name='inventory_l_student_3e92e1_idx'),
        ),
    ]
