# Generated by Django 6.0.3 on 2026-04-29 16:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_journalrecord_grade_and_more'),
        ('users', '0002_alter_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='slot',
            name='inventory_s_teacher_d45cf3_idx',
        ),
        migrations.AddField(
            model_name='course',
            name='discount_milestones',
            field=models.JSONField(blank=True, default=dict, help_text='Логіка: {"85": 5, "91": 10, "96": 15}. Ключ — мінімальний бал для отримання відсотка знижки.', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='inventory.discipline'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='inventory.course'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='earned_discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='is_discount_used',
            field=models.BooleanField(default=False, help_text='True, якщо бонуси за цей курс уже були використані для оплати пакета'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='users.student'),
        ),
        migrations.AlterField(
            model_name='curriculumlesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_lessons', to='inventory.topic'),
        ),
        migrations.AlterField(
            model_name='journalrecord',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='inventory.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='inventory.package'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='inventory.slot'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.student'),
        ),
        migrations.AlterField(
            model_name='package',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='users.student'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='inventory.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='inventory.discipline'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='inventory.course'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.teacher'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'discipline'], name='inventory_c_is_acti_d1ad7c_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecompletion',
            index=models.Index(fields=['student', 'is_discount_used'], name='inventory_c_student_fef074_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['student', 'status'], name='inventory_p_student_869b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['teacher', 'start_time', 'status'], name='inventory_s_teacher_530bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['teacher', 'created_at'], name='inventory_t_teacher_5ddee3_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursecompletion',
            constraint=models.CheckConstraint(condition=models.Q(('earned_discount__gte', 0), ('earned_discount__lte', 100)), name='check_valid_earned_discount'),
        ),
        migrations.AddConstraint(
            model_name='coursecompletion',
            constraint=models.CheckConstraint(condition=models.Q(('completed_lessons_count__gte', 0)), name='check_positive_completed_lessons'),
        ),
        migrations.AddConstraint(
            model_name='journalrecord',
            constraint=models.CheckConstraint(condition=models.Q(('grade__isnull', True), models.Q(('grade__gte', 1), ('grade__lte', 10)), _connector='OR'), name='check_valid_grade_range'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='check_positive_package_balance'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='check_valid_slot_time_range'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='check_positive_transaction_amount'),
        ),
    ]
