# Generated by Django 6.0.3 on 2026-05-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_packageplan'),
        ('users', '0004_student_money_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('english', 'Англійська мова'), ('math', 'Математика'), ('ukrainian', 'Українська мова'), ('history', 'Історія України'), ('informatics', 'Інформатика')], max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('preferred_days', models.CharField(blank=True, default='', max_length=200)),
                ('preferred_time', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('matched', 'Підібрано викладача'), ('cancelled', 'Скасовано')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_requests', to='inventory.package')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_requests', to='users.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
