# Generated by Django 6.0.3 on 2026-05-22 08:57

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_lessonmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalrecord',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_answers/%Y/%m/', validators=[api.validators.validate_file_size, api.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='homework_status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='homework_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
