# Generated by Django 6.0.3 on 2026-05-23 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_journalrecord_homework_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonmaterial',
            options={},
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_materials', to='inventory.teacher'),
        ),
    ]
