# Generated by Django 6.0.3 on 2026-05-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_lessonmaterial_options_and_more'),
        ('users', '0006_student_check_positive_money_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursecompletion',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('teacher', 'start_time')},
        ),
    ]
