# Generated by Django 6.0.3 on 2026-05-31 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('inventory', '0013_complaint'), ('inventory', '0012_merge_0008_material_0011_alter'), ('inventory', '0014_merge_0012_and_0013'), ('inventory', '0015_alter_lessonmaterial_options_and_more'), ('inventory', '0016_remove_journalrecord_homework_file_and_more'), ('inventory', '0017_alter_learningrequest_level')]

    dependencies = [
        ('inventory', '0012_alter_coursecompletion_unique_together_and_more'),
        ('users', '0006_student_check_positive_money_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='inventory.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='users.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.AlterModelOptions(
            name='lessonmaterial',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='journalrecord',
            name='homework_answer_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='journalrecord',
            name='homework_file',
        ),
        migrations.RemoveField(
            model_name='lessonmaterial',
            name='file',
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='homework_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='learningrequest',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
