# Generated by Django 6.0.3 on 2026-05-26 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_merge_0008_material_0011_alter'),
        ('inventory', '0013_complaint'),
    ]

    operations = [
    ]
