# Generated by Django 6.0.3 on 2026-05-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_merge_0012_and_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonmaterial',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='journalrecord',
            name='homework_answer_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
