# Generated by Django 6.0.3 on 2026-05-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_lessonmaterial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalrecord',
            name='homework_file',
        ),
        migrations.RemoveField(
            model_name='lessonmaterial',
            name='file',
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='homework_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
