# Generated by Django 6.0.3 on 2026-05-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_journalrecord_homework_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrequest',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
