# Generated by Django 6.0.3 on 2026-06-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('inventory', '0018_alter_package_course_nullable'), ('inventory', '0019_journalrecord_lesson_topic'), ('inventory', '0020_package_low_balance_notified')]

    dependencies = [
        ('inventory', '0017_alter_learningrequest_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.course'),
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='lesson_topic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='journalrecord',
            name='homework_file_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='low_balance_notified',
            field=models.BooleanField(default=False),
        ),
    ]
