# Generated by Django 6.0.3 on 2026-06-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_journalrecord_lesson_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='low_balance_notified',
            field=models.BooleanField(default=False),
        ),
    ]
