# Generated by Django 6.0.3 on 2026-06-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_complaint_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalrecord',
            name='homework_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
